{
 "title": "Integrations Tracers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "INVOICES BATCH LOG",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_invoices_batch_log_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOADED INVOICES",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_loaded_invoices_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFTP BATCHS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_invoices_batch_log_sftp_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP BATCH",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_invoices_batch_log_http_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRACERS",
   "type": "traces",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "6453e3b8c10109adc7c9d07616b5950b"
    }
   ]
  }
 ]
}